SELECT i.REST_ID,
    REST_NAME,
    FOOD_TYPE,
    FAVORITES,
    ADDRESS,
    ROUND(AVG(REVIEW_SCORE),2) as SCORE
FROM REST_INFO as i
JOIN REST_REVIEW as r
    ON i.REST_ID = r.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY REST_NAME
ORDER BY SCORE DESC, FAVORITES DESC
