SELECT MEMBER_NAME,
    REVIEW_TEXT,
    date_format(REVIEW_DATE, '%Y-%m-%d') as REVIEW_DATE
FROM REST_REVIEW as r
JOIN MEMBER_PROFILE as m
    ON r.MEMBER_ID = m.MEMBER_ID
WHERE r.MEMBER_ID IN(
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
        SELECT MAX(CNT)
        FROM (
            SELECT COUNT(*) as CNT
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
        ) A
    )
)
ORDER BY REVIEW_DATE, REVIEW_TEXT